### PR TITLE
WIP Autosense then loop

### PR DESCRIPTION
**Pull request by jotomo**
Overview still sees no COB data at times (overview is updated once a minute in the example)
image

### CODE REVIEW

**Comment by MilosKozak** [comment]
add debug to places  where `null` is returned for sensitivity data

**Comment by MilosKozak** [comment]
did you find the reason?

**Comment by jotomo** [comment]
Sorry, didn't get around to locking into this further yet ...

**Comment by jotomo** [comment]
Closing for now, will open another PR without debug commits when I have something usable.

**Pull request closed without merging**
