### PR TITLE
Inclusion of the new watch face "AAPSv2" 

### PR DESCRIPTION
**Pull request by andrew-warrington**
Features: 
1) has larger text
2) shows COB 
3) allows to choose between showing phone battery level (AAPS) or rig battery level (OpenAPS) via watch Settings menu

Most changes are either minor or are completely new files. The largest changes were to the WatchUpdaterService.java, which required several new blocks of code in order to expose COB, IOB, and current temp basal independently of the main status string.

### CODE REVIEW

**Comment by andrew-warrington** [comment]
Forgot to mention in the description of the pull request: I tested the other round watch faces as well to ensure the updates to the WatchUpdaterService.java did not break any of them. (I could not test rectangular watch faces as I don't have a rectangular watch!)

**Comment by AdrianLxM** [comment]
Hi @andrew-warrington, looks great.
And great that you want to help with the wear part.
I'll be travelling the next couple of weeks a lot so sorry in advanced for delays in response time.

A few remarks:

* IOB, COB in my opinion is rather part of the status (it is sent in the status line as well) and not of a single BG. So I would put it in `sendStatus()` rather then sending it with the single BG values. In fact, I think attaching it to the BG values could lead to sending old data. The wear plugin listenes on the bus for events and sends the status on certain events and the BG on other events. With a new BG it will get passed to the watch but IOB and COB might not be calculated based on that BG. -> send it with the status.

* In order to avoid code duplication (we already have enough of that already and we will need to switch to a new communication protocol in the foreseeable future, so maintainability ... well), it would be great to not copy the base watchface but just add the new features. You can check in the layout e.g. if a certain element exists or not (if `findViewById` returns `null`l) and adapt to it.

cheers,
Adrian

**Comment by MilosKozak** [comment]
the battery option shoud distinguish nsclient and aaps mode?

**Comment by andrew-warrington** [comment]
@MilosKozak thank you. Are you saying that the battery option should default differently, i.e. if AAPS mode then it should show the phone battery, whereas if NSClient then it should default to the rig battery? (As an aside, I was thinking of adding the option to show both batteries, but not sure if anyone would want that and it will use up space.)

@AdrianLxM great feedback thank you. Just a clarification to make sure I understood about the base watch face: You are referring to not duplicating the specific file BaseWatchFace.java, right? I.e. Keep Home2.java and all my new *2.xml files? That way, I would not destroy the original watch face for those who like it.

I will probably start over with my work on the WatchUpdaterService -- I did quite a lot of "fishing around" and experimentation in the code to make it work. I am sure I can do it more cleanly from scratch while addressing your comment about sending IOB/COB along with status.

**Comment by andrew-warrington** [comment]
This is an interim commit & push only to make sure the work is backed up. Please do not review this version; another commit will come next week, with the BaseWatchFace2.java removed and the BaseWatchFace.java updated to incorporate its code.

**Comment by andrew-warrington** [comment]
@AdrianLxM in this commit I have addressed your comments above. The changes to BaseWatchFace.java are considerable, as I tried to make it somehow more "universal".

I have a concern about the final product, and that is that is to do with the new preferences and the potential for confusion. On some watch faces the preference "Show loop status" means infusion rate and IOB. On my new face you can switch off infusion rate and IOB each separately in the preferences, but in those older watch faces it won't actually switch them off, since they are included within Status. I get somewhat the same issue with Delta and AvgDelta. Both are shown in the preferences now, but if you have Delta off and avgDelta on, neither of them will show up... because avgDelta is dependent on Delta in the way the base watch face is coded.

Should I modify the existing watch faces which depend on BaseWatchFace as well, to make them compatible with those new preferences?

**Comment by andrew-warrington** [comment]
@AdrianLxM @MilosKozak this PR is complete from my point of view, and ready for review and further testing. I remain available for bug fixes and code improvements where needed. 

As mentioned in my comment further up, I have regression tested the old watch faces and I believe I have not broken anything. That said, I did not update the old watch faces to make them responsive to the new preferences I implemented.

**Comment by AdrianLxM** [comment]
@andrew-warrington, I have two remakrs:


***1) when testing the app, it crashes:***

```
12-01 16:30:33.718 6249-6249/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: info.nightscout.androidaps, PID: 6249
                                                 java.lang.RuntimeException: Unable to start service info.nightscout.androidaps.plugins.Wear.wearintegration.WatchUpdaterService@9e217c7 with Intent { act=info.nightscout.androidaps.plugins.Wear.wearintegration.WatchUpdaterService.Resend cmp=info.nightscout.androidaps/.plugins.Wear.wearintegration.WatchUpdaterService }: java.lang.StringIndexOutOfBoundsException: length=0; regionStart=0; regionLength=-1
                                                     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3411)
                                                     at android.app.ActivityThread.-wrap21(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1632)
                                                     at android.os.Handler.dispatchMessage(Handler.java:110)
                                                     at android.os.Looper.loop(Looper.java:203)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6251)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
                                                  Caused by: java.lang.StringIndexOutOfBoundsException: length=0; regionStart=0; regionLength=-1
                                                     at java.lang.String.substring(String.java:1931)
                                                     at info.nightscout.androidaps.plugins.Wear.wearintegration.WatchUpdaterService.sendStatus(WatchUpdaterService.java:557)
                                                     at info.nightscout.androidaps.plugins.Wear.wearintegration.WatchUpdaterService.resendData(WatchUpdaterService.java:344)
                                                     at info.nightscout.androidaps.plugins.Wear.wearintegration.WatchUpdaterService.onStartCommand(WatchUpdaterService.java:138)
                                                     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3394)
                                                     at android.app.ActivityThread.-wrap21(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1632) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                     at android.os.Looper.loop(Looper.java:203) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6251) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```
You seem to use data for `openApsStatus` that is only available when compiling AndroidAPS as NSClient and using it with an external OpenAPS rig. Hence the `substring()` call will crash.

Could you please give me an example string of what it should look like and what your substring (`openApsStatus`) should look like than I will try to find something equivalent in AndroidAPS.

***2) Could you please give a short explaination what the new fields are?***
 "time with an circle or arrows", ..."H", "L"... thank you!

The cockpit looks great! It's really good to get some more modern designs :D 

cheers, Adrian

**Comment by andrew-warrington** [comment]
Hi @AdrianLxM thanks so much for the review! Now I know what my testing blind spot was. Yes, I was always compiling NSClient only.

The openApsStatus is the number of minutes since the last loop (as differentiated from the number of minutes since the last glucose reading). As I am an OpenAPS user I looked for a way to show that value. I should do that differently; if AAPS is the APS then the number should come from there, or a blank string e.g. "--" should be sent. (The user can switch off this field in the preferences if it is no use to them.) I would appreciate your help or suggestion there; I can then fix it.

The new fields:

- "H" is the label on a LED light which will illuminate yellow in the cockpit when glucose goes above the High threshold. sgvLevel == 1 is the trigger.

- "L" is the label on a LED light which will illuminate red in the cockpit when glucose goes below the low threshold, as above. sgvLevel == -1 is the trigger.

For the two above, I needed to initialise the TextView in the BaseWatchFace so that I could change the background image in the Cockpit.java code as appropriate. I didn't want to pollute BaseWatchFace with this code specific to 1 watch face, but I couldn't figure out a better way.

- The circle with the apparently-barely-visible arrows :P contains the number of minutes since the last loop (i.e. the openApsStatus field discussed above). It changes from green to red when the last loop is too old.

So let me know if you have any suggestions around openApsStatus, and in the meantime I'll try to figure it out for myself.

(Not that we want to have a million different watch faces, but I am building another one for a future PR... this time the inspiration is somewhat more steampunk and analogue.)

**Comment by AdrianLxM** [comment]
@andrew-warrington I opened a PR against your `dev`. I know you allowed us to push to your branch directly, but I think it is better this way:
https://github.com/andrew-warrington/AndroidAPS/pull/1

It gives me back my finer granularity for the delta (preference for that) and solves the NPE when running AndroidAPS as loop. I tested it with "BigChart" and the circle watchface. This way it has at least no functionality changes.

As the status is only sent when there is an update, I guess it would be good to send/calculate a timestamp and send it to the watch. This way the watch can age the number without needing constant updates?

**Comment by andrew-warrington** [comment]
Alright, @AdrianLxM I merged that PR and tested -- was not sure how to test without merging. I am getting a crash now in the app, when compiled as NSClient. Seems to be linked to the changes in wear preferences on the app side. I will look more carefully and fix later tonight. 
`
11-26 09:04:01.529 23349 23349 E AndroidRuntime: FATAL EXCEPTION: main
11-26 09:04:01.529 23349 23349 E AndroidRuntime: Process: info.nightscout.androidaps, PID: 23349
11-26 09:04:01.529 23349 23349 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{info.nightscout.androidaps/info.nightscout.androidaps.PreferencesActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getIntExtra(java.lang.String, int)' on a null object reference
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2678)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2743)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4560)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.app.ActivityThread.-wrap19(ActivityThread.java)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6165)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getIntExtra(java.lang.String, int)' on a null object reference
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at info.nightscout.androidaps.PreferencesActivity$MyPreferenceFragment.onCreate(PreferencesActivity.java:123)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.app.Fragment.performCreate(Fragment.java:2336)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:949)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2036)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.app.FragmentController.dispatchCreate(FragmentController.java:165)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.app.Activity.onCreate(Activity.java:964)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.preference.PreferenceActivity.onCreate(PreferenceActivity.java:536)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at info.nightscout.androidaps.PreferencesActivity.onCreate(PreferencesActivity.java:47)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6687)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2631)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	... 10 more
`

**Comment by andrew-warrington** [comment]
@AdrianLxM , the PreferencesActivity.java NPE above is no longer occurring. I didn't change any code, just uninstalled and reinstalled the app and opened the preferences screen. 

However the app still crashes every 10 minutes or so, here:

`12-01 23:33:02.417 24992 24992 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean info.nightscout.androidaps.plugins.Loop.LoopPlugin.isDisconnected()' on a null object reference
12-01 23:33:02.417 24992 24992 E AndroidRuntime: 	at info.nightscout.androidaps.receivers.KeepAliveReceiver.checkPump(KeepAliveReceiver.java:85)
12-01 23:33:02.417 24992 24992 E AndroidRuntime: 	at info.nightscout.androidaps.receivers.KeepAliveReceiver.onReceive(KeepAliveReceiver.java:55)`

What do you think? This code is completely unrelated to the changes you or I made in this PR, so I am not sure what is causing it to crash now. I did a pull in Android Studio today after merging your PR. I thought I was getting it from origin-dev (my fork), but could that have led to me pulling down new code from the upstream-dev repo as well, in which has a new bug introduced?

I like the change you made for detailed delta; better than just cutting off the decimal without recourse like I did. As regards the sending of a timestamp rather than the minutes ago for openApsStatus, I agree, better design. Will try to dig into that in the morning!

**Comment by AdrianLxM** [comment]
@andrew-warrington I believe this `isDisconnected()` is coming from upstream. I believe, I did some changes there for the local alerts.

Could you please open an issue with a full stacktrace (if you can get it). Thanks

**Comment by andrew-warrington** [comment]
@AdrianLxM done -- https://github.com/MilosKozak/AndroidAPS/issues/514

**Comment by andrew-warrington** [comment]
Ok, crash is fixed with https://github.com/MilosKozak/AndroidAPS/pull/515. I will now work on sending the timestamp for openApsStatus instead of the number of minutes.

**Comment by andrew-warrington** [comment]
Crash mentioned above about PreferencesActivity is back, and logged as issue https://github.com/MilosKozak/AndroidAPS/issues/517.

**Comment by andrew-warrington** [comment]
@AdrianLxM, I have had a major mess up of my git repository and am wondering whether you would agree to merge this PR now, so that I can delete my local repo and fork a new one from Dev. I have just spent about 3 hours wanting to do further work but have been struggling with a non-cooperating git...

I don't think this PR has any major bugs in it now that you corrected the NPE. It does need to have the "openApsStatus" topic fixed but I would do that in the next round.

**Comment by AdrianLxM** [comment]
@andrew-warrington, I've merged it, but not to `dev` but to a branch `watchfaces`. So you can fork the repo and work from that branch.

**Comment by andrew-warrington** [comment]
I have completed work on this PR against the branch watchfaces, in PR https://github.com/MilosKozak/AndroidAPS/pull/519.

**Pull request merged**
