### PR TITLE
Start KeepAliveService after pump init.

### PR DESCRIPTION
**Pull request by jotomo**

### CODE REVIEW

**Comment by AdrianLxM** [comment]
At the moment the method `startKeepAliveService()` also starts the execution services for the pumps
Shouldn't they be started before doing the first read cyle from the pump?
I guess starting them would need to be moved up.

What is the reason behind not starting the keep alive before everything else?

**Comment by jotomo** [comment]
_KeepAliveReceiver_ may or may not trigger an instant call to _Pump.refreshDataFromPump_, which then runs before the explicit initialization ..

**Comment by MilosKozak** [comment]
if touch the services i'd hook starting pump services to `setEnabled`

**Comment by AdrianLxM** [comment]
Included in: https://github.com/MilosKozak/AndroidAPS/pull/486

**Comment by jotomo** [comment]
Resolved via  #486.

**Pull request closed without merging**
