### PR TITLE
Combo: allow records created by the combo to be merged with existing records.

### PR DESCRIPTION
**Pull request by jotomo**
So far, the Combo driver operated under the assumption that pump records where only ever created by a pump and that records are immutable. Therefore, creating a record that collided with an existing record was an error situation. 

Now that treatments are merged together from NS, carb entries and pump records (and hacks to work around clashes of timestamp ids within the same second), this holds now longer true. The error messages observed have all been false positives and where confined to the Combo. 

This PR changes the Combo driver to not insist on unique records, but lets the _TreatmentsPlugin.getPlugin().addToHistoryTreatment_ method take whatever action is suitable to create or update the DB.

Since I don't have a setup that can reproduce this, this needs to be tested:
1) normal boluses should still be added properly (shouldn't be an issue)
2) bolusing from the pump and immediately after giving a bolus from AAPS should be rejected, stating that the bolus was calculation based on outdated data
3) and of course during pump init the bogus error messages should be gone.

How to test: go to menu _VCS->Git->Remotes..._, add a new remote with name _jotomo_ and URL `git@github.com:jotomo/AndroidAPS.git`. Then, _VCS->Git->Fetch_, followed by _VCS->Git->Branches_ and checkout branch _jotomo/upstream-11482+1489_. Build and deploy as normal.

Initial assessment: https://github.com/MilosKozak/AndroidAPS/issues/1482#issuecomment-427333965

### CODE REVIEW

**Comment by jotomo** [comment]
Travis build failure is unrelated.
#1482 #1489 @tKostka @thomasmenges @andyrozman

**Comment by MilosKozak** [comment]
@tKostka @thomasmenges any news?

**Comment by tKostka** [comment]
I made my comments to the test in the wrong issue, sorry, please look here:
https://github.com/MilosKozak/AndroidAPS/issues/1482#issuecomment-429613325

> @jotomo I did a short test with your branch, no issues. Please let me know if this is what you need or if i should some more testing. Attached are logs and screenshots (I changed the language from german to english at the end of the test).
>
> 10:58 AM: opened the wizzard in AndroidAPS and let it give 0.3 units as correction
> 11:23 AM: given 0.2 units on the combo (without AndroidAPS) and then tried to make a Bolus with 0.2 units with AndroidAPS -expected Alarm appears
> 11:36 AM: same as 11:23 but with 0.1 units
>
> logs-screenshots_Bolus_20181014.zip

**Comment by jotomo** [comment]
@tKostka Thanks for testing!

**Pull request merged**
