### PR TITLE
Replace some png icons by vector

### PR DESCRIPTION
**Pull request by Philoul**
I created some vector icons to replace png (mainly in overview)
Not finished but I can make new ones from time to time...
I didn't delete original png files (I don't know if you want to keep them or not...)

### CODE REVIEW

**Comment by MilosKozak** [comment]
look these icons the same?

**Comment by Philoul** [comment]
Yes, I just redraw the icons in vector with Illustrator (Vector is easier to handle with code, i.e. change color or manage different screen size...)
On high definition screens we don't see the difference, but on low resolution it is a little sharper.

**Comment by Philoul** [comment]
I found some low resolution icons (16x16px): 
add
as
clone
remove
I don't know if you want to keep original design... (see below proposal, first line I tried to be as close as possible to current icons, second line it's closer to current "look" of others icons)
add-remove

**Comment by Philoul** [comment]
See below all vector icons and screenshots (just maybe AS icon a little bit to dark, I used same color than in Overview, but it's easy to lightened it...)
vector_icons
Screenshot_20200615-185930_AndroidAPS

**Comment by MilosKozak** [comment]
ok, remove replaced icons pls

**Comment by Philoul** [comment]
I will continue to vectorize the remaining icons
If on your side you wish new icons, do not hesitate to send me what you want, even a draft (I am not a "designer" but I often create vector cliparts from bitmap for my wife that is teacher...)

**Pull request merged**
