### PR TITLE
WIP: Support rotary input on wear

### PR DESCRIPTION
**Pull request by jotomo**
Enables entering amounts (carbs, bolus, TT) via rotary input (aka crown) on watches with a physical crown.

Tested in emulator only, due to lack of hardware.

### CODE REVIEW

**Comment by wootmasterslick** [comment]
Great! Anyone here with crowned watch that can test?

**Comment by quizzmaster** [comment]
I can test it this evening or on the weekend

**Comment by jotomo** [comment]
@quizzmaster That'd be great! If you're using Android Studio 3.4, there's a new _Pull Requests_ tool window, which allows to easily create a local branch from a PR (thus manually adding additional git remotes isn't needed), see https://blog.jetbrains.com/idea/2018/10/intellij-idea-2018-3-eap-github-pull-requests-and-more/

**Comment by quizzmaster** [comment]
@jotomo that's a really useful feature :blush:

I've tested this PR and it works as intended. Sometimes it's a bit hard to select the correct number, because the scrolling is really sensitive, but that might depend on the crowns sensitivity :sweat_smile:

**Comment by jotomo** [comment]
> I've tested this PR and it works as intended. 

Thanks!

> Sometimes it's a bit hard to select the correct number, because the scrolling is really sensitive, but that might depend on the crowns sensitivity

 I thought that might happen, but unfortunately input speed/momentum data is not available (nor can it be inferred from the delta), which might be used to ignore input below a certain threshold of movement.

**Comment by quizzmaster** [comment]
@jotomo 
> I thought that might happen, but unfortunately input speed/momentum data is not available (nor can it be inferred from the delta), which might be used to ignore input below a certain threshold of movement.

Fortunately it's manageable although it's not as easy as the touch input.

**Comment by jotomo** [comment]
@quizzmaster On second thought, just because the API doesn't provide _speed_ data, doesn't mean it can't be detected :-)
Could you test again? Detected speed is printed to console, so you can experiment with the _threshold_ variables if needed.

**Comment by gregorybel** [comment]
looks quiet interesting, any watch to suggest with crown?

**Comment by jotomo** [comment]
Needs more work, closing for now.

**Comment by wootmasterslick** [comment]
Did you make any  progress with the sensitivity? I am about to get a Fossil sport with rotary crown so perhaps I can do some testing for you.

**Pull request closed without merging**
