### PR TITLE
Autosens fix

### LINKED ISSUE #1182: Autosens shows "Autosens deactivated"
After switching to the OpenAPS Oref1 Sensitivity Plugin, the sensitivity is shown shortly in the OpenAPS SMB Tab, but is then shown as "Autosens deactivated".

### PR DESCRIPTION
**Pull request by triplem**
Should fix #1182. 

@jotomo could you please review it shortly?

### CODE REVIEW

**Comment by triplem** [comment]
Revert the last change, and now try to call the latest AutosensData for the "current" variable. Seems to work now. Could be, that this bug is also in the oref0 plugin, but this is not fixed.

**Comment by MilosKozak** [comment]
so the only change now is to call it synchronized? https://github.com/MilosKozak/AndroidAPS/pull/1183/files#diff-caca8d8281d898e69d67edeb3651482cR74
@triplem

**Comment by triplem** [comment]
The change is really the call to getLastAutosensDataSynchronized instead of getAutosensData(time). This delivers the latest one, whereas the previous call returned null, because it is looking for the one based on the given time.

**Comment by typ1-brods** [comment]
Same behaviour when using Oref0, average or AAPS algorythm. Showing 'Autosens deactivated' in script, but in settings it is enabled. It is working one time after changing the algorythm, then 'deactivated'

**Comment by MilosKozak** [comment]
for me it's definitely better. merging

**Comment by MilosKozak** [comment]
hmmm it was wrong. you call detection to cuurent time not to `toTime`

**Pull request merged**
