### PR TITLE
ProfileSwitch on graph depending on ScreenSize

### PR DESCRIPTION
**Pull request by PoweRGbg**
Text size in ProfileSwitch events depends on screen resolution

### CODE REVIEW

**Comment by MilosKozak** [comment]
looks good . can you paste here some screenshots for different resolutions?

**Comment by PoweRGbg** [comment]
image
Resolution 1440-2560
image
Res: 768-1280

These are emulated only

**Comment by MilosKozak** [comment]
could you create screenshot of emulated Jelly mini phone?

**Comment by AdrianLxM** [comment]
Jelly before:
screenshot_20171203-114956

Jelly after:
screenshot_20171203-115546

Looks great!

**Comment by AdrianLxM** [comment]
For the Jelly there will be a few other things needed. Like making it scrollable as with IOB in the lower chart the upper one just vanishes in portrait mode (landscape is fine as it switches to a scrolling layout):
screenshot_20171203-114934
... or making the dots for the chart smaller that they don't overlap that much.

Nevertheless: Roumen's PR looks good!

**Comment by AdrianLxM** [comment]
Hi @PoweRGbg, I did a PR to your branch: https://github.com/PoweRGbg/AndroidAPS/pull/3

It adapts the drawings to very small screens:

screenshot_20171203-135504

As you have your test set-up for larger screens already set up, could you please test, if they also work on them. 
Thank you!

**Comment by MilosKozak** [comment]
let's make it ready for merge :)

**Comment by RadoslavR** [comment]
Is it possible to have a line under the label down. Or will this be just a label?

**Comment by PoweRGbg** [comment]
@AdrianLxM your comit is merged. I'll post a high-res screenshot in a few minutes

**Comment by PoweRGbg** [comment]
Here are 2 screenshots (portrait/lanscape) on high-res 
screenshot_20171204-104402
screenshot_20171204-104433
Is the BGgraph supposed to be gone in lanscape ?

**Comment by AdrianLxM** [comment]
Thank you @PoweRGbg. That was my mistake. Here is an update: https://github.com/PoweRGbg/AndroidAPS/pull/4

**Pull request merged**
