### PR TITLE
Add icons to CP (@PoweRGbgs work)

### PR DESCRIPTION
**Pull request by AdrianLxM**
* adding icons

### CODE REVIEW

**Comment by AdrianLxM** [comment]
I did a bit of cleanup and tested it on a 2.4 inch phone:
screenshot_2016-01-01-02-18-52 screenshot_2016-01-01-02-18-33

Thanks @PowerGbg and to who donated the icons :D

**Comment by PoweRGbg** [comment]
Remove line #67 at app/src/main/res/layout/actions_fragment.xml to remove extended bolus colour

**Comment by AdrianLxM** [comment]
Todo: Move "pump site change" to category "pump" and "Openaps Offline" to category "CGM & OpenAPS"

**Comment by PoweRGbg** [comment]
Done in 
https://github.com/PoweRGbg/AndroidAPS/blob/picture-renaming/app/src/main/res/layout/careportal_fragment.xml
screenshot_1500725808

**Comment by AdrianLxM** [comment]
Thanks @PoweRGbg I pulled that change in. Where would you put temp-target? is it PUMP or is it OPENAPS?

**Comment by PoweRGbg** [comment]
As it's more commonly used we may move it to Activity & Feedback - substitute it with  "Note" button

**Comment by PoweRGbg** [comment]
Like this :)
screenshot_1500729570

**Comment by MilosKozak** [comment]
👍

**Comment by MilosKozak** [comment]
i want it. ready to merge? :)

**Pull request merged**
