### PR TITLE
Dev strings

### PR DESCRIPTION
**Pull request by Heiner1**
Word "Tratments" edited

### CODE REVIEW

**Comment by AdrianLxM** [comment]
thanks

**Comment by Heiner1** [comment]
Has "1 check failed" something to do with the Travis build check error? 
I found in bg translation some unfamiliar first line in /values-bg/strings.xml: 
<?xml version="1.0" encoding="utf-8"?>

**Comment by AdrianLxM** [comment]
@Heiner1 there has been a closing tag too much in the bulgarian translation. Fixed by @swissalpine. Please update your branch :)

**Comment by Heiner1** [comment]
@AdrianLxM  Thanks, I saw it now ; swissalpine committed it nearly the same

**Pull request merged**
