### PR TITLE
Create CONTRIBUTING.md - First draft of contribution guidelines

### PR DESCRIPTION
**Pull request by dlvoy**
Hi, as new developer i struggle a little bit with first steps - maybe contribution guideline will help me and other devs to bootstrap into contributors community :) This guide below is only starting point - from things I've already learnt (hopefully got that right)

### CODE REVIEW

**Comment by Philoul** [comment]
I approve this initiative. This has already allowed me to see that on my first 2 PR, I did not apply all the steps described in this (first) guide...

In addition, what could be useful for developers who discover the application, it would be (even simple) a documentation or specification of the application : global structuring of files, of code, of plugins, NS / xDrip / wear interfaces... and also the main rules to apply

**Comment by Philoul** [comment]
Maybe the right place to have "contributing guidelines" is in wiki ...
=> There is already a page about "Pull Request", we could add a chapter for developers, I think ...

**Comment by dlvoy** [comment]
> Maybe the right place to have "contributing guidelines" is in the wiki ...
> => There is already a page about "Pull Request", we could add a chapter for developers, I think ...

The mentioned article is about how to modify wiki (docs) themselves. I thought about some developer guides, about code conventions, project organization, Pull Request but for the codebase, how to test source code, etc. - not sure if it should be bound with the user manual, which is meant for end-users, translated - or to have it together with source code, where devs live :)

**Comment by Philoul** [comment]
Yes I'm agree with you... I would like to adapt wear watch development in Tizen os for my galaxy watch and this kind of documentation could help me...
the wiki talk just a little bit of development in "How I can help" section... that's why I have suggested to add a "development chapter" in wiki...

**Pull request merged**
