### PR TITLE
Get MAC-address from ruffy

### PR DESCRIPTION
**Pull request by jotomo**

### CODE REVIEW

**Comment by jotomo** [comment]
@TebbeUbben

**Comment by jotomo** [comment]
ruffy part (later) at https://github.com/MilosKozak/ruffy/pull/8

**Comment by MilosKozak** [comment]
@jotomo what's the state of this PR?

**Comment by jotomo** [comment]
PR is done and tested. Requires updating Ruffy as well (this PR has a fallback to not crash when ruffy version is outdated and asks user to update ruffy in that case). 
Targets `database` branch and should be done together with that change. Benefit is the ability to dedup data based on pump MAC and treatment date/id; potentially useful for OPEN.

**Comment by jotomo** [comment]
Ctrl-Z

**Pull request closed without merging**
