### PR TITLE
DanaR.comm tests

### PR DESCRIPTION
**Pull request by PoweRGbg**
this one should be ok

### CODE REVIEW

**Comment by MilosKozak** [comment]
sorry but could you remove so many trash commits?
backup current state
```
git checkout dev
git checkout -b backup
```
consolidate (assuming main repo is upstream)
```
git fetch upstream
git checkout dev
git reset --soft upstream/dev
git checkout -am "DanaR tests"
git push -f origin dev
```

**Comment by MilosKozak** [comment]
i could do it but it would be commited with my name

**Comment by PoweRGbg** [comment]
That should work. Thanks for the help with git

**Comment by MilosKozak** [comment]
thanks

**Pull request merged**
