### PR TITLE
Change Headertext size in Overview Carb dialog to fit languages like german 

### PR DESCRIPTION
**Pull request by osodebailar**
The headertext size is too large for header text in other languages like german "Kohlenhydrate".
The text does not fit and was displayed as 'Kohlenhy-'
Changed the textsize from large to medium

### CODE REVIEW

**Comment by jotomo** [comment]
@osodebailar Please provide a screenshot. "Kohlenhydrate" should not appear unabbreviated on the overview screen.

**Comment by osodebailar** [comment]
3d5706cb-b1a9-4022-b454-52996eec0913

**Comment by jotomo** [comment]
Ah, in the dialog. I missed that part. I'll take care of it (the PR actually doesn't contain any changes ;-) ).

**Comment by osodebailar** [comment]
Changed to 
f0d33110-288f-4151-bc61-e7754adaf1ed

**Comment by MilosKozak** [comment]
no code here. should it be issue?

**Pull request closed without merging**
