### PR TITLE
Display carbs required

### PR DESCRIPTION
**Pull request by twain47**
Add option to expose carbs suggestions provided by the SMB algorithm as a local notification.

### CODE REVIEW

**Comment by MilosKozak** [comment]
@AdrianLxM this is not part of https://github.com/MilosKozak/AndroidAPS/pull/1950 (latest master). Do we allow this change.
Basicaly the idea is good.
How is this solved in OAPS?

**Comment by twain47** [comment]
In OpenAPS this information is sent to the user using a pushover notification

**Comment by twain47** [comment]
In OAPS the full text of rT.reason is sent to the user if carbsReq > 0 (which is returned) however that seemed a bit verbose in this case.

**Comment by AdrianLxM** [comment]
A minor change: Once it is carbs*Required* and once it is carbs*Requested*.

Also I'm not sure if we should use the openloop notifications or the standard ones?

**Comment by MilosKozak** [comment]
i'd say separate notification. it's usefull in closed loop as well

**Comment by twain47** [comment]
I would have liked to have made the carbs suggestions appear at the bottom of the overview screen  in the same style as open loop suggestions but I couldn't work out how. Would be very grateful if someone could point me at how that works and so I can make that change.

**Comment by MilosKozak** [comment]
open loop button requires special handling.
We could display it next COB and create notifications in urgent cases

**Comment by jotomo** [comment]
@twain47 OpenAPS has the _carbsReqThreshold_ (see _SMBDefaults_) to avoid triggering this too frequently, which users coming from OpenAPS are probably gonna request next. Furthermore, I'd expected more user requests for more configurability (sound, override silent, snooze ...).  For alerts there probably needs to be something like snoozing once the alarm is confirmed, since (in my observations) _carbsReq_ can stay up until an upward trend is observed, despite carbs being administered. 
The point I'm trying to make: just fetching the data and displaying it is just the start. Ideally and IMHO the whole idea deserves to be fleshed out (and dare I say designed) before being implemented and pushed to users to accommodate real-life use cases including alarm fatigue(!) and an option to temporarily silence the alert (this applies to existing local alerts for connection issues as well).
That being said, hooray for a carbs required alert!

**Comment by twain47** [comment]
@jotomo Adding carbsReqThreshold seems reasonable. We always ran OpenAPS with it set to 1 so got the expected behaviour. I'll try and get that added later.

The snooze, etc. don't seem to be much of an issue for us at the moment (we have been running with something like this patch for about 3 weeks). It hasn't been my experience that it can stay on after an upwards trend - possibly a difference in how AAPS triggers the loop? At the moment the alert is very (overly?) subtle which means most the the other issues don't really cause a problem. The main issue is missing the alert altogether.

However, the main issue, I'm not an experienced android developer. Adding alert options, dismiss, etc. is probably outside my current ability.

**Comment by Tornado-Tim** [comment]
I have been running this, for about a day or so, and havnt found the alarms to be annoying, infact I have been more appreciative of the extra warning.

But yes, the ability to snooze and have a threshold for it to trigger the alert first is a good idea.

**Comment by wootmasterslick** [comment]
Its been a while. What is the current status of this? Love to see it in AAPS.

**Comment by twain47** [comment]
> Its been a while. What is the current status of this? Would love to see it in AAPS.

Yes, you're right. I'll update the PR as per feedback.

I got involved in other things and didn't come back to it.

**Comment by twain47** [comment]
Screenshot (10 Mar 2020 12_21_01)

Added next to COB (as suggested) but space is a bit tight for meaningful text

**Comment by guydavies** [comment]
Hi Brian,

That looks cool.  Why not abbreviate to (+21g in 44min)?  You could even remove the + because it relates to COB and you only show requirements in brackets.

Rgds,

Guy

**Comment by wootmasterslick** [comment]
Abbreviating it might make it harder to understand for less technical users, so
if there is enough space I think you could leave it as is.  Looks very good! 
Is there also a notification triggered if the prediction becomes “critical” ?

**Comment by twain47** [comment]
> Is there also a notification triggered if the prediction becomes “critical” ?

There is a notification and you can specify the threshold (number of carbs) before it is triggered.

**Comment by twain47** [comment]
@AdrianLxM @MilosKozak 
I think this is updated based on current feedback and rebased onto dagger3.

**Comment by Tornado-Tim** [comment]
@twain47 can you change the base to dev? all merging work will now be done on that branch.

**Pull request merged**
