### PR TITLE
Fix Reset Button in Local Profile that doesn't work

### PR DESCRIPTION
**Pull request by Philoul**
In latest dev when you start to modify a local profile and you want to reset your modifications, "Reset" Button doesn't work... (We have to close local profile window and open it again to see original values)
I think it's just a missing `build()` in code to fix it...

### CODE REVIEW

**Comment by MilosKozak** [comment]
this is correct
https://github.com/MilosKozak/AndroidAPS/commit/d7f9208acf76154cff3ed2e0e15e26d084abb918
thanks for finding this bug

**Comment by Philoul** [comment]
Just closed, not merged?

**Comment by guydavies** [comment]
it looks like it's merged into Dev as the release shown in Milos' response. I guess it was just an accidental omission of stating merged by Milos.

**Comment by Philoul** [comment]
Ok, thank's Guy...

**Pull request closed without merging**
