### PR TITLE
AndroidAPS 2.6

### PR DESCRIPTION
**Pull request by chrisharris751**

### CODE REVIEW

**Comment by chrisharris751** [comment]
2.6

**Comment by MilosKozak** [comment]
@chrisharris751 be carefull what you do especially with this code

**Comment by MilosKozak** [comment]
@chrisharris751 i explicitly declared i don't want to see this on public places (inlcuding your repo)

**Comment by chrisharris751** [comment]
Apologies Milos. This was unintentional. I will get rid of it.

Regards

Chris Harris

**Pull request closed without merging**
