### PR TITLE
Setting to play alerts as notification / 100% music stream

### PR DESCRIPTION
**Pull request by anbraten**
Having error sounds played as media was quite unhandy (esp when you are in a call). I changed the audio stream to notification, so you can set you phone in DND mode and be able to leave your media volume untouched. A media stream should IMHO only be used for foreground activities / actions (playing music / watching a movie).

#1304

### CODE REVIEW

**Comment by MilosKozak** [comment]
@AdrianLxM does this have any side effects?

**Comment by AdrianLxM** [comment]
Hi @anbraten,

thanks for your PR! It indeed seems like the proper way to not use the `AudioManager. STREAM_MUSIC` volume.

It would affect the behaviour that people are used to with alarms (e.g. having AAPS alarms at night while still being on silent for phone calls).

The possibility to have this for one app (or just one notification type of an app) exists on newer phones - but deeply hidden in notification setting sub-menus and only accessible if you click on items that don't even look actionable.

We should therefore have this feature go through proper beta/RC stages. Sorry that we will only merge it after the upcoming release.

We should then have a simple "override silentmode" option for the user.

Did you test the behaviour of `AudioManager.STREAM_ALARM` volume?
If that would also meet your needs - I prefer going with default Android configurability.

**Comment by anbraten** [comment]
Hey @AdrianLxM,

> It would affect the behaviour that people are used to with alarms (e.g. having AAPS alarms at night while still being on silent for phone calls).

It seems there are two cases:

- AAPS should not disturb (eg. meeting, driving a car, theater, ...)
- AAPS should even disturb when phone normally in silent mode (eg. sleeping)

> The possibility to have this for one app (or just one notification type of an app) exists on newer phones - but deeply hidden in notification setting sub-menus and only accessible if you click on items that don't even look actionable.
> We should then have a simple "override silentmode" option for the user.

I agree with you, AAPS should not depend on some special functions which currently aren't implemented by most manufactures at all.

> Did you test the behaviour of AudioManager.STREAM_ALARM volume?
> If that would also meet your needs - I prefer going with default Android configurability.

I tried `STREAM_ALARM` as well, but the problems is still that I am scared about unexpected notifications in some situations. ;) My clock alarms are only set on special times at which I am normally not working.

Right now I would suggest  we use `STREAM_NOTIFICATIONS` as suggest in my PR as default and add an option "override silent mode" which will set it to `STREAM_MUSIC` with full volume.

In the long term I will maybe create a PR of a notification rework based on the `persistentNotification`, so you could end an alarm / mute it like you can do in xdrip+.

**Comment by anbraten** [comment]
I added an option to turn off the `Play alerts with 100% volume as music stream` setting. It is normally enabled to keep the known behavior.

**Comment by MilosKozak** [comment]
@AdrianLxM I'd prefen not adding more options. What is the common way to do it ? How is it done in Dexcom app?

**Comment by wootmasterslick** [comment]
You can have a look in the old sightremote app from TebbeUbben. I believe pump errors were handled quite well there.

**Comment by EknalpTiel** [comment]
So you find a solution to geht this in Version 2.6?

**Pull request closed without merging**
