### PR TITLE
Safety loop

### PR DESCRIPTION
**Pull request by AdrianLxM**
To make it more easier to grasp what my intention in https://github.com/MilosKozak/AndroidAPS/issues/681 was.

What would you think of an approach like this?

I'm not 100% sure if starting the safety-invoke on a new Thread like this will work. It should be on another thread as the callback happens on the CommandQueue-Thread.

### CODE REVIEW

**Comment by MilosKozak** [comment]
what is the `safety` for?

**Comment by AdrianLxM** [comment]
It will disable SMB in the run. This way on the bug where no SMB is delivered it will fall back to Oref0 and not give the 0-TBR where it expects there are SMBs

**Comment by AdrianLxM** [comment]
On my test-run:
eventualBG: 122mg/dl
target: 90mg/

At first it set a 30% TBR.
Then it tried to do a SMB of 0.2U - failed
-> safety run with SMB deactivated
Then it set a TBR of 260%.

So it actively prevents low-temping when actually more insulin should be given (but bolusing fails).

**Comment by AdrianLxM** [comment]
In addition: Starting the thread like this works! :)

**Comment by jotomo** [comment]
Thoughts, no solutions:
* 'safety' is not a good name to convey the intent. _forceTbrOnly_, _preventSmb_, _tempBasalFallback_?
* Might it be clearer to pull the `tempBasalRequested` and `bolusRequested` checks into LoopPlugin? (Someone called me did a lazy job there)
* Thread.sleep() and concurrent invocations, from a new BG (Combo is slow if e.g. TBR/SMB has to wait for a pump basal profile update if a profile switch ended), manual invocations from the user ... some synchronization needed?

**Comment by AdrianLxM** [comment]
@jotomo 
1) I renamed "safety" to "tempBasalFallback". Good idea

2) Could you elaborate a bit please.

3) The `SystemClock.sleep(1000);` only adds one more second. So I wouldn't focus on that. But you are right, there might be "parallel" loop invocations. Not only now but already before with a manual loop trigger, a treatment change event, ... just with a lesser likelihood.
Do you think it suffices to synchronize `LoopPlugin#invoke()`?

**Comment by jotomo** [comment]
2) & 3) are refactorings which also touch this PR, but were there before.

2) The `ConfigBuilder.applyTBR/SMBRequest` methods return immediately, without invoking the callback, when `request.tempBasalRequested` or `request.bolusRequested` are false. This was ok-ish before, but now that it matters more whether one of those is actually executed, it might make the code clearer to pull those checks from those methods and have `LoopPlugin.invoke` do those checks and only invoke the respective method if we know we have work for them (like is done in ~335 to set the `waiting` state for the UI).
3) I think synchronization will be sufficient (A `synchronized` method can invoke itself since it holds the lock, right?). Adding some _cancel an earlier request if we have a new one_ logic would likely be hard to reason about and prone to errors. With synchronization the loop will run multiple times in short succession, but that shouldn't happen too often and does no damage.

**Comment by AdrianLxM** [comment]
Ok, I synchronized the loop invocation. Yes, a synchronized method can call another one (on the same object) and therefore also itself recursively, as both synchronize to `this` and therefore hold the lock. In this case it would even be the callback thread, that does that.

On the other topic: I think it is ok, if `ConfigBuilder.applyTBR/SMBRequest` return without callback if there is no request. But we should check if there is the possibility of a SMBRequest without a TBR request.

**Comment by AdrianLxM** [comment]
@jotomo so this should do it: https://github.com/MilosKozak/AndroidAPS/pull/925/commits/e79ef7f0186c759d99b5eedc2931c4da7f0e3feb ?

**Comment by jotomo** [comment]
Yes.

**Comment by AdrianLxM** [comment]
No invocation on treatment works fine.
Jotomo already used this for a while.

**Pull request merged**
