### PR TITLE
Watchfaces direct tap actions

### PR DESCRIPTION
**Pull request by Philoul**
Direct Tap Actions from watchface:
=> Code is concentrate in BaseWatchFace file (except for BigChart, Circle and NoChart WF)
=> immediate vibration feedback added (@dlvoy you were right, it's really better...)
=> Tap zones adjusted according to chart size and position (ex no DOWN zone in AAPSv2, no CENTER zone in BigCHART...)
=> I will prepare an image to show zones in each watchface
Comments added (espacially in BaseWatchFace file for each new functions)
Commits done to facilitate code review

### CODE REVIEW

**Comment by Philoul** [comment]
You can see in image below available zones in each watchface:
- BG= Background zone : this zone is allways available to access to main menu
- No DOWN zone available to AAPSv2 and Steampunk watchface (note: in AAPS Watchface, I left DOWN zone because size is enough to be launched easily on my TicWatch pro, but if it's too difficult on too many watches, I can delete it...)
- No CENTER zone in BigChart, and width of LEFT/RIGHT zones a little bit reduced
- Size of zones are slightly adjusted for watchfaces with chart to avoid overlapping
- default TOP action is Main menu, No action for other zones

watchfaces_2

And my settings in preferences: 

screen 36

**Comment by rICTx-T1D** [comment]
@MilosKozak: please,  give feedback for reasons how this pull was not merge?

**Comment by Philoul** [comment]
Just update with latest dev to remove conflict

**Comment by Philoul** [comment]
@rICTx-T1D you can test it and give me a feed back...
I'm using an improved version of AAPS V2 watch face (see https://github.com/MilosKozak/AndroidAPS/pull/2334). I Closed first PR for poor compatibility of text size, and split it into 3 seperate PR : This one (for Direct Tap Action) and 2 other for Color improvement and Bolus / Carb overlap in graph... 
May be if other users think these are good improvements they will be merged...

I think my current setting is easy to memorize because linked to background informations:
Top (BG value) : Temp Target
Left (COB zone) : Extended Carb
Right (IOB zone) : Bolus
Center (Hour zone) : Calculator (in the middle of Carb and Bolus...)
And I always can access to main menu if necessary on top left or top right but I very rarely use it now...
I think it's a cool improvement (much quicker to set a bolus or launch calculator from watchface...) and default setting is close to current watch face (main menu in all zone)

**Pull request closed without merging**
