### PR TITLE
Ask to confirm first profile switch

### PR DESCRIPTION
**Pull request by TebbeUbben**
Related to #1103

### CODE REVIEW

**Comment by AdrianLxM** [comment]
I believe the case where the profile switch is coming from either Nightscout or the local Profile is missing.

**Comment by MilosKozak** [comment]
it's going to be very hard make use friendly if data comes on background from NS

**Comment by AdrianLxM** [comment]
@MilosKozak it would only be the first time. Basically when setting up AndroidAPS. After that it should never warn again. (Unless the user presses "cancel")

**Comment by TebbeUbben** [comment]
How about showing that dialog on the first time a profile plugin is activated?

**Comment by schmitzn** [comment]
>How about showing that dialog on the first time a profile plugin is activated?

I guess this would be the easiest way for the implementation.

But I think (for the users) it would be better to show the dialog on the first time when the pump profile is actually going to be overwritten. We could use a notification in the overview section with the ability to open the yes/no dialog. So this notification would appear before the basal profile on the pump is being changed. As long as the notification wasn't accepted, the user would have to stay on the unchanged profile.

Maybe it would also be a helpful option to make it possible to import the pumps profile within the setup wizard.

**Comment by MilosKozak** [comment]
OK. let's keep it as it now here. Maybe I'd add link to wiki. what do you think?

**Comment by AdrianLxM** [comment]
The real problem was the profile coming from Nightscout.
And most of the trap we have already eliminated by needing a profile switch.

**Comment by AdrianLxM** [comment]
How about:
 * Virtual Pump as default pump in Config Builder
 * Warning as soon as the user wants to switch to a real pump that this means overwriting the basal settings.

?

**Comment by jotomo** [comment]
Since you user isn't acknowledging a single profile update on the pump, but accepts that AAPS will take control of the pump's basal rate profile hereafter (when and how often it is updated is a detail), asking for confirmation when enabling a pump plugin seems to be a good place.

**Comment by MilosKozak** [comment]
ok, this could be a soulution

**Comment by AdrianLxM** [comment]
Superseded by https://github.com/MilosKozak/AndroidAPS/pull/1168

**Pull request closed without merging**
