### PR TITLE
Fix prefs NPE

### PR DESCRIPTION
**Pull request by jotomo**
Addresses Crashlytics issue http://crashes.to/s/79ccb421103

### CODE REVIEW

**Comment by jotomo** [comment]
Bug is triggered by opening the preferences after application start.

**Comment by AdrianLxM** [comment]
:+1: tested merged into the localalerts branch. Works! :)

**Comment by MilosKozak** [comment]
could you cherry pick to dev?

**Comment by jotomo** [comment]
@MilosKozak Done.

**Pull request merged**
