### PR TITLE
Watch strings

### PR DESCRIPTION
**Pull request by Philoul**
I have to do the same in complications files (strings created)
I have to check watchfaces (but very few strings in them...)
I tried to modify interactions/utils/DisplayFormat.java (for some units) but it doesn't work in it (???)
Hope everything is good...

### CODE REVIEW

**Comment by MilosKozak** [comment]
is it tested on watch?

**Comment by Philoul** [comment]
Not yet
I still do not master Android Studio and debugging tools ...
To test the AAPS changes, I generate a full version apk that I manually install on the smartphone (I know it's not optimized), but I do not know yet how to do the same thing with the apk of the watch wear-full-release.apk :-(

**Comment by dlvoy** [comment]
Unit tests are green, but I will try to test it on a real watch.

Updating DisplayFormat is tricky due to unit tests I guess, probably would require `aaps.gs` which is equivalent to `MainApp.gs` function ( instead `getResources().getString(...)`) and accompanied mock to test if it works for other locales.

I can take over and modify DisplayFormat - question how to sync that work? Do a PR to your fork or wait till this PR is merged and do it later as PR to main repo?

**Comment by Philoul** [comment]
Thank's dlvoy,
I started to replace getResources().getString by MainApp.gs in java files

I have a question : I found some strings in Layout rect or round_activity_home_2.xml (IOB and carb) and in modern_layout (no status)…
Should I replace text strings in these file ? (i.e. android:text="carb"   =>   android:text="@string/activity_carb" )

**Comment by Philoul** [comment]
@dlvoy  I propose you finish and check if everything is ok after this PR is merge... As I do not master well github yet, I'm afraid to do silly things if you do a PR on my fork... (It's new for me...)

**Comment by dlvoy** [comment]
Ok, sounds like a plan!

**Comment by MilosKozak** [comment]
and is it running on real watch?

**Comment by dlvoy** [comment]
I've just tested it on the real watch (first merging locally dev to it and adding some PL translations, to test on other than EN locale) - and it works nicely! 
I had only one issue with the layout in the main menu, when my translation was too long:
too-long-translation
In attachments zip with a patch that fixes that (by enabling autosize for labels in newer APIs):
fixed-layout
@Philoul can you copy, merge and push it here? :)

**Patch:** [wear-patch-for-main-menu.zip](https://github.com/MilosKozak/AndroidAPS/files/3943901/wear-patch-for-main-menu.zip)

**Comment by MilosKozak** [comment]
create PR with the patch

**Comment by dlvoy** [comment]
Here you go #2262 :)
_I was confused, this change can be applied independently!_

**Pull request merged**
