### PR TITLE
Adding out_units support for determine-basal.js

### PR DESCRIPTION
**Pull request by kakoni**
Currently determine-basal displays results in mg/dl.
This behaviour can be changed by setting profile.out_units to mmol/L

This PR picks the current units from Profile and if its mmol, it sets out_units accordingly.

### CODE REVIEW

**Comment by MilosKozak** [comment]
converting units is not available for MA

**Comment by MilosKozak** [comment]
target dev branch please

**Comment by kakoni** [comment]
Hi @MilosKozak, not sure whats wrong with MA?

**Comment by MilosKozak** [comment]
support for `out_units` is not here

**Comment by MilosKozak** [comment]
looks good, thanks

**Pull request merged**
