### PR TITLE
fix for carbs and wizard dialogs on screen rotation

### PR DESCRIPTION
**Pull request by PoweRGbg**

### CODE REVIEW

**Comment by MilosKozak** [comment]
checkboxes are not restored

**Comment by PoweRGbg** [comment]
On my emulator they work. Do you have problems with the checkboxes in NewInsulinDialog also ?

**Comment by MilosKozak** [comment]
in emulator it works. wondering why it's not necessary to restore checkboxes and radiobutton state but you have restore TextEdits
any idea @jotomo @AdrianLxM ?

**Comment by MilosKozak** [comment]
hmm looks like there is default `android:saveEnabled = "true"`
then you don't need to save state right @PoweRGbg ?

**Comment by jotomo** [comment]
Default controls restore state for me. @MilosKozak We're not directly using _TextView_, but _NumberPicker_. We may need to extend _NumberPicker_ to restore the state of its children.

**Comment by MilosKozak** [comment]
@jotomo do you know how to do it without changing all dialogs. we must be able to disable this behavior for dynamicaly generated dialogs

**Comment by jotomo** [comment]
Hm, https://github.com/jotomo/AndroidAPS/commit/8f871b362057078a2eb4f5f4c457b9e841403bbd

**Comment by MilosKozak** [comment]
is it part of some PR?

**Comment by jotomo** [comment]
Nope, just a quick commit to see if it works (yes) and how we like this approach :-)

**Pull request merged**
