### PR TITLE
PumpDanaR unit tests

### PR DESCRIPTION
**Pull request by PoweRGbg**
another try

### CODE REVIEW

**Comment by PoweRGbg** [comment]
No idea! Resources  is included and it builds locally OK

**Comment by MilosKozak** [comment]
missing
`import android.content.res.Resources;` in `AAPSMocker.java`

**Comment by PoweRGbg** [comment]
Done! and codecov is nice :)

**Comment by MilosKozak** [comment]
your latest fixes are not there

**Pull request closed without merging**
