### PR TITLE
[#1806] Making white bar from Wear OS face match watchface background

### PR DESCRIPTION
**Pull request by dlvoy**
[#1806] For WearOS app, added option to make white status bar match background of whole watchface and blend in, switchable on Settings -> Matching divider

### CODE REVIEW

**Comment by dlvoy** [comment]
Merged dev and fixed conflicts to have it merge-able after recent complications addition which refactored a little bit wear target.

What i did not understand why it shows such decline in coverage - is it inherited from merged dev changed? Since besides sync-merge of dev and small fixes in 4-6 places in wear target - nothing really changed :confused:

**Comment by MilosKozak** [comment]
do you have screenshots of both?

**Comment by dlvoy** [comment]
For AAPSv2, all variants (light&dark, with or without matching divider):
AAPSv2_dark_divider
AAPSv2_dark_nodivider
AAPSv2_light_divider
AAPSv2_light_nodivider

**Comment by dlvoy** [comment]
For AAPS, all variants (light&dark, with or without matching divider):
AAPS_dark_divider
AAPS_dark_nodivider
AAPS_light_divider
AAPS_light_nodivider

**Comment by dlvoy** [comment]
For AAPS(Large), all variants (light&dark, with or without matching divider):
AAPSLarge_dark_divider
AAPSLarge_dark_nodivider
AAPSLarge_light_divider
AAPSLarge_light_nodivider

**Pull request merged**
