### PR TITLE
[WIP] Autotune plugin v2

### PR DESCRIPTION
**Pull request by Philoul**
2nd version of Autotune Plugin (I use it since about 15 days and results seems to be ok for me, but be very carefull if you test it, I DO NOT consider it as validated today)
=> My main work today is to build datasets to be able to do real "validation" of results in different situations
=> Results are not identical with oref0-autotune, but when I check detailled calculation, iob calculated by oref0-autotuneprep are not consistent with iob calculated by AAPS (???). I prefer to use aaps algorythm for consistency of calculation...
=> Limitation with this version are the same than for oref0-autotune (only one single IC and ISF value). May be future updates after validation of a first version of autotune for full circadien profiles...
=> I list some "Todo" in the beginning of AutotunePlugin.java file (some of them are required before a first released version in AAPS, other could be done in future)

Sorry for hundreds of commits

Feedback would be appreciated...

### CODE REVIEW

**Comment by chrisbev** [comment]
Hi what a wizzo plugin. I was about to test a PR in latest dev and saw the AT plugin so decided to try/evaluate this as well.  It looks good but I wondered what the 'Miss.' column was? Is high/low number good/bad? I thought I was merging PR2706 into the dev but unfortunately I seem to have just the PR on an old dev will try a dev build next to see. I'm using Insight so is Absolute values setting important?

**Comment by Philoul** [comment]
"Miss" is missing days for basal rates calculation (equivalent than red bar in autotuneweb mail)
I use insight too. absolute setting is important for autotune web because oref0 code doesn't take "rate" information in mongodb table. (so you can't compare AAPS results with AutotuneWeb results if not set.)
I have a "patched version" of oref0 autotune to test and compare results. And in log folder, I added 2 autotune subfolder to be able to run oref0 autotune with aaps data that includes absolute rates.You also have a zip file for each autotune run of AAPS plugin for detailled analysis and oref0 compare.
When I get treatments with AAPS plugin, I get this "absolute values" for TBR (but this should be verified with other pumps and other settings, you can verify in aaps-treatment files in autotune subfolder...)

You can send me a PM on gitter if you need help...

**Comment by Philoul** [comment]
For "Missing days" analysis, small value is "better" for basal rate tuning
i.e. if you selected 10 days for autotune and miss days is 2, that means that 8 days are used for basal rate tuning.
On the other hand if for another BR value you have 8 or 9 missing days, that means that you have only 1 or 2 days for this basal rate tuning (tuning is done with previous and next BR tuning values for missing days). But that also mean that these hours are probably close to meals (with COB) or you have important bg variation, these data are used to tune IC/ISF values...)

**Comment by chrisbev** [comment]
How can I check I have the latest please? I've  2.6.7-beta1 dfaf3f86f from PR2706 but history log seems to indicate that was a bit ago and 0-4hrs missed readings looks important? At the moment in AS I show all all files/versions and checkout the PR is there a way to checkout a particular committed version? NB I can't find out how to PM unless I have to create a room first?

**Comment by Philoul** [comment]
@chrisbev I sent to you a private message on gitter if you need more information to test this plugin.
I updated this PR 2 days ago with current dev.

**Comment by Philoul** [comment]
Conversion to Kotlin done for main modules
Fix some issues (some crash in specific situation and mmol units)
Several UI improvements (now calculation is done in background and shows intermediate results)

Only for tests, do not use for looping (the results are not entirely consistent with oref0Autotune and after several tests, I think that the results are not as stable as those of oref0 ...)
I have to analyse iob calculation (detailled compare with oref0 calculation), and work on unit tests...

**Comment by chrisbev** [comment]
Built 2.6.7-beta1 eaf0163da if I try and run more than one day get Error in input data,  try to reduce the number of days.
Can't seem to post pics here?

**Comment by chrisbev** [comment]
Just a thought will it go back historically or will I have to gather say 7 days then look/run?

**Comment by chrisbev** [comment]
Turned through midnight and now will run 2 days.
Good and feedback as I go (may be early if still experimenting?)
Line all columns up: Heading basal ISF IC etc. (and DIA in #2822)?
I would prefer the number of 'Hits' rather than number of Misses.
Is there a reason '%' has '/' rather than another column? Or will it be say '2/7 | +2%' eventually?
That begs the question to include a '+' or not?.
Will there be say a select tick box to select which are copied to local profile as I certainly would rather only copy some, say good hit rates/low misses, or another reason?

**Comment by Philoul** [comment]
@chrisbev I'll try to answer all your questions...
1) Error in input data : It seems to be the same issue I had a few weeks ago see https://github.com/MilosKozak/AndroidAPS/issues/2708 => You can check in your history browser, if you select a day before 3 or 4 days ago, and you don't get COB curves, it's the same issue (probably any day before july 14th...). It's not in autotune plugin and I can't solve it (I my case I just waited and each new day I was able to add one more day in autotune run)...
=> I still have the problem today if I want to see a day before june 5 (but it works on my dev phone????), probably a complete uninstall and reinstall of AAPS could solve this issue but I prefered do nothing and wait...

2) Line all columns up: Heading basal ISF IC etc. (and DIA in #2822)? In first version I tried to aligned them but it was a little complicated. I have this improvement in my todo list and #2822 will help me but it's not my priority today (see below...)

3) I would prefer the number of 'Hits' rather than number of Misses. We can (nb Hits = nb selected days - nb missing days), I selected missing days because in oref0-autotune we have this information, so it's easier to compare results. But it remains a possible improvement for later...

4) Is there a reason '%' has '/' rather than another column? Only the space available on a line in my dev phone (it's a low res phone). If the line is too long, the result does not fit on one single line and it becomes difficult to read.
If I only had my loop phone (high res screen), I would probably have chosen your proposal, but I tried to find the best compromise even for low res phone (but we can probably improve it)

5) Will there be say a select tick box to select which are copied to local profile ? Today autotune is a whole and consistent calculation (even if number of days is low, BR levels are adjusted and that only means it is periods with COB and meal and probably IC / ISF are more important than Basal rates for these hours). This possibility of "partial selection" is not available today in oref0-Autotune and I didn't planned to add it (I even think that it could be dangerous in some cases)
=> If you think results are good, you can active whole profile 
=> If you think it should be manually tuned, I chose to add a "Copy to local profile" button, that way you can adjust each value
=> Milos added in dev recently a "Profile Helper" activity, later I'll try to interface autotune with it (you can compare profiles)

Thank's a lot for your comments, that help me. Today my 2 priorities are 
1) work on detailled analysis of IOB calculation, root algorythm are the same between oref0 and aaps but I have important gaps between aaps internal calculation and oref0-autotune calculation (final results are sometime close but they are less stable I think in aaps plugin than in autotuneweb so warning included in this plugin still remains very important today)
2) work on unit tests to be able to verify and validate in different situation that autotune output result (with one single IC and ISF value) are always better than input profile
Of course if you find other bugs I'll try to solve them if I can...

**Comment by chrisbev** [comment]
Good PR but ISF on mmol is in other units see pic:-

**Comment by Philoul** [comment]
@chrisbev I can't see your screenshot, can you send me autotune zip file (in log folder) and screenshot as pm in gitter please?
I thought I fixed the mmol units bug but there is obviously still work to be done ...
Thank's

**Comment by Philoul** [comment]
@chrisbev I found several bugs in unit management when you use mmol...
Today the only autotune result close (not identical) to original autotuneweb calculation is when everything is in mgdl (profile units AND main setting units)
=> if profile units or main application units or both are set to mmol, results are completely wrong (basal rates and ISF value) due to incorrect convertion (internal calculation in aaps is done with mgdl units...)

Thank's a lot for your feedback, I will be focused on solving these bugs in my next update...

**Comment by JohnKitching** [comment]
I don't really understand how branches interact so apologies for this ...

Is this based on the main branch?

I'm currently testing 2.7 RC3, if I switch to the Autotune branch will I go backwards in functionality?

I'd like to help if I can and I'm a mmoller so might be able to.

**Comment by Philoul** [comment]
All synchronisation between branches are done manually...
This PR is not ready today to be included in a futur release, but each time you see in the list of commits `Merge remote-tracking branch 'Milos/dev' into Autotune_Dev_v2`, it's a synchro of my working autotune branch with the latest updates of dev branch...
As you can see my latest synchro was done 2 days ago and includes all updates and functionnalities available in RC3 (except the version's reference not updated)
=> Be carefull if you test this Plugin,  I currently use standard aaps iob calculation but there are some modifications in oref0 iob calculation for autotune, and I'm still working on it to understand how detailled calculation is done... It's quite difficult for me because I'm not a specialist of oref0 code...
So even if results are sometimes close to autotuneWeb, this plugin is not validated today and do not use it for loop, only for tests and feedback...

**Comment by JohnKitching** [comment]
Thanks for that. 
I think I'll wait for the next version. 
Your efforts are much appreciated, I think this will be a great addition to AAPS.

**Comment by chrisbev** [comment]
Hi just to double check. With web AT I believe the recommendations are for the actual time period (say hour interval) so I would change the pump hour period basal one hour earlier to allow for the insulin to have effect. Does AAPS AT do this in the recommended new profile?

**Comment by Philoul** [comment]
No, don't change anything in your profile, Insulin DIA and peak is integrated in AT calculation.

**Comment by chrisbev** [comment]
Thanks. Still very much like the plug-in but some feedback from my prospective. Not yet fully using but always manual tweaks to my profile. When profiles are saved to local it is in the deaded American format mmddyy and the confusion for me is 070620 June or July when used sometime later and forgotten. Is scientific format an Android format yyyymmdd hh:mm? Secondly and maybe on your list but I have 3 IC time zones could there easily be a pop-up asking if would like to go to 1 or leave uncorrected or factor them all?

**Comment by Philoul** [comment]
@chrisbev For CopyLocal, I use same date format than other "CopyLocal" functions (it's a local format), on my phone (France) it's jj/mm/yyyy hh:mm (Same than Clone profile in Treatment tab/profile switch), may be you have a wrong setup on your phone local format... For IC  Autotune works with only one IC and one ISF value, so if you have several IC or ISF values, I calculate a "24h average" of all values as starting point (I though it was a better than first IC or ISF value)...

**Comment by chrisbev** [comment]
Hi @philoul. Thanks found setting I had to set AAPS to System default language as English is apparently US date format. Now to my suggestion for future work for me ISO format would be preferable so sorting gives most significant to least significate dates i.e. yyyy/mm/dd as used in the loop/smb tabs. I can see for you mm/dd/yyyy sorts/lists fine except over a year change. NB Raised #2942 to suggest adding US after English as took me ages to find in fact ever since I started looping so years! Cheers...

**Comment by chrisbev** [comment]
Hi just an observation on the last build compared to the previous the recommendations are about 15% higher for my overnight zero misses time. The previous had recommended a bit of a reduction which was inline with what I was going to do so reduced my basal a bit. I've moved to the new NS database and data now getting to NS so will soon be able to compare with webAT but have an error so reaching to FBook for help.

**Comment by Philoul** [comment]
Yes it's because I changed categorize_uam_as_basal management to be consistent with oref0 algorithm.
I opened a PR on oref0 project to propose previous management but Scott explained in it's answer than current management was decided to improve convergence. (see https://github.com/openaps/oref0/pull/1384#issuecomment-685292611)
I will propose some log messages updates and probably Autotune documentation updates because doc can be improved concerning uam management (setting is only for persons who don't enter any carbs during a day, if there is at least one meal entered, all uam data will be categorized as basal (that's why now you have an increase of basal rates)
I still have to change iob calculation to have good basal rates...

**Comment by chrisbev** [comment]
Cheers, I now have webAT giving results so if you would like me to compare after your update let me know. I enter most meal carbs with only a few I don't, have one ISF and 3 CR timezones. In the mean time I think I'll go back to the previous build as nearer to my body situation?

**Comment by Philoul** [comment]
New PR done https://github.com/nightscout/AndroidAPS/pull/34

**Pull request closed without merging**
