### PR TITLE
NS to local Profile copy

### PR DESCRIPTION
**Pull request by PoweRGbg**

### CODE REVIEW

**Comment by triplem** [comment]
I did already implemented something like this in #1541. We should join forces on this one. What do you think?

**Comment by PoweRGbg** [comment]
I agree. This could be the step forward in all-in-one profile

**Comment by MilosKozak** [comment]
@triplem 's code seems to be cleaner. could you add missing parts (and add tests if possible)

**Comment by PoweRGbg** [comment]
Closing until I fix the conflicts

**Pull request closed without merging**
