### PR TITLE
WIP: Autotune Plugin review

### PR DESCRIPTION
**Pull request by Philoul**
Sorry for hundred of commits (I don't know today how to clean and group these commit in github)
This is a first share of my work on Autotune plugin.
=> Everything is in java (today I'm not fluent with kotlin...) (I added a litlle documentation of this plugin into autotune folder)

For testing this plugin, I export all files (input profile, bg values, treatments, prepped data, tunedprofiles for each loop, logs) with the same format than oref0 (everything is as close as possible to original oref0-autotune function
=> That way I can compare each step, each intermediate results with oref0-autotune that runs on a virtual machine

- Inputs exported data from aaps are 98% consistent with NS queries used by oref0 (but aaps exported data are better than those used by oref0...). Gaps comes from Insight pump (extended bolus have additionnals entries in NightScout that change a little bit oref0 autotune results, minor impacts)
- AutotunePrep results are close to oref0-autotune-prep but still remains some litlle gaps that comes from iob calculation (I use internal aaps algorythm and not an adapted algorythm of oref0 one). Today I don't know if we can trust these results or not (see check convergence below) but I'm quite confident...
- AutotuneCore is 100% consistent with oref0-autotune-core results (if I run oref0-autotune-core with prepped data and input profiles generated by aaps, I have exactly the same results with 3 digits...)

Next steps are:
- check convergence (I'll integrate a loop for running several times autotune and see if it converge or not with very low profile, very high profile...)
- wider tests with other configurations (other pumps, other profiles, ...)
- add profile switch and integration with local profile
- improve user interface (it takes about 20s for 15 days, and 1 min for 30 days) I tried to add a feedback for each day calculation but I don't know how to do that
- check all dagger integration and autotunePlugin structure (I couldn't manage to directly include @Singleton classes directly in constructor...
- nothing is crypted (I don't know if it's necessary or not), all exported files are for external analysis

I need some feedback and some help with this first step...

### CODE REVIEW

**Comment by Philoul** [comment]
Now I'm using IobCpbCalculatorPluginHistory and TreatmentPluginHistory for iob calculation.
=> Results are closer to oref0-autotune but not full consistent... (see image below with 15 days)
=> Main gap is for CarbRatio... (other data are quite close)
AutotuneCompare

IobCalculation is now very slow (I think it's necessary to run autotune in background in a dedicated thread and not in foreground as it is) (#10min for 15 days calculation, with several alerts from Android AAPS not responding...)
I'll make further test with oref0 (today exported data from AAPS are consistent with NS data, I'll try to add neutral TBR when no TBR is running). Scott Leibrand tells me that Autotune can incorrectly calculate IOB if data are missing (profil basal rate) between two 2 TBR...

**Comment by nielsmaerten** [comment]
This already looks great. Kudos!  
I'd be happy to do some testing if you ever need someone using an Insight pump

**Comment by Philoul** [comment]
Plugin is still unusable as is, with latest commits, calculation duration is about 10min for 15 days on my phone...
- I have to include calculation in dedicated thread to not freeze AAPS during calculation time.
- Results requires a validation (today I can't trust results, it still remains significant gaps with oref0-autotune)
- Be very carefull with Insight pumps (during my development I made several cross tests with oref0-autotune running on my computer on a virtual machine, and now (only for Insight pump), I don't trust oref0-autotune results anymore! With current master, some input datas are missing or are wrong in NS (according to AAPS settings) for having good results, I'll test again settings and results with latest AAPS updates...
I'm still working on this plugin and I hope soon better news (I have more time than usual to work on it because of Covid...)

**Comment by Philoul** [comment]
replaced by https://github.com/MilosKozak/AndroidAPS/pull/2706

**Pull request closed without merging**
