### PR TITLE
#2969 new stylish watchface

### PR DESCRIPTION
**Pull request by rICTx-T1D**
Hi folks,

how in https://github.com/MilosKozak/AndroidAPS/issues/2969 describe, I have spend some hour to write a new watchface.
After some problems with positioning, I changed all to relativ layout.

Then I have make the following resolution tests in AVD emulator:
- 416x416x1.28"  (Fossil Gen5 and similar)
- 454x454x1.40" (Fossil Gen4, Fossil Sport and similar)
- 320x320x1.2"   (Skagen Falster 2  and similar)
- 402x476x1.91" (Oppo Watch (Rect format - not Quader)   and similar)
- 390x390x1.2"  (LG Moto 360  and similar)

I make hardware tests with my real watch:
- 416x416x1.28"  (Fossil Gen5)

Please accept this pull request. Otherwise give feedback to improve it.

Best regards
rICTx-T1D

### CODE REVIEW

**Comment by rICTx-T1D** [comment]
I'am sorry but I don't understand why the codecov checks are failed. I start all unit-tests and all test was passed successfully.  Can anyone help to correct this problem, when it is important to approve this pull.

**Comment by Philoul** [comment]
@rICTx-T1D be patient please.
Milos has a lot of things to do concerning AAPS and I think his priority today is not the addition of a new watchface just before a new major release (2.7.0)
Once checked by several tester with different watches, if it's ok, it will probably be included in a future release... But that takes time.
Don't bother with "codecov checks", sometimes it's good, sometimes not (I don't really understand how it works but I think it's an overall indicator of the whole code quality). The most important things to verify are that build works and your modifications too.
I will try to test your watchface (I just need to find some time for that...), and I'll give you a feedback.

**Comment by dlvoy** [comment]
I will try to look at it after release 1.7.0 is live on production - we are currently busy preparing release, most features should be frozen and only bug fixes merged. I have some other work to do wear side of AAPS and few other PRs waiting in queue (@Philoul 
 i have not forgotten, only shifted efforts to mainline AAPS ;) ),
so please be patient ;)

Additionally - I really appreciate your work and ingenuity you've put into design, but I am against "designed by" taking up valuable place on dial.

**Comment by rICTx-T1D** [comment]
Hi @dlvoy,
the words "designed by" are NOT included in code or picture. I has only insert it, on screenshot here in github issue and chat. I have see that's other doesn't use it. I'am understand, that deployment of version 2.7.0 is higher prio at the moment, but it's be really nice, when anyone can check my pull request after the big run is leaved.

In gitter-chat I ask some people to test my watchface on physical watch and leave a comment here.

**Comment by Philoul** [comment]
@dlvoy I still have in mind the "improved version" of AAPS v2 I proposed in january https://github.com/MilosKozak/AndroidAPS/pull/2334 (I use it every days and I'm very happy with it), do you think if I replace "default font" by a dedicated font as @rICTx-T1D did in this PR, we can avoid compatibility issue you reported to me https://github.com/MilosKozak/AndroidAPS/pull/2334#issuecomment-577087313 with your watch (font size and position) ?

**Comment by rICTx-T1D** [comment]
@Philoul 
In WearOS design guide the roboto font-family is called as primary font element. 
See https://designguidelines.withgoogle.com/wearos/style/typography.html

So I want use it, to make the watchface independently from manufacture settings and preference.

**Comment by rICTx-T1D** [comment]
Merging is successfully on new repo-location

**Pull request closed without merging**
