### PR TITLE
Wear nullprofile fix

### PR DESCRIPTION
**Pull request by AdrianLxM**

### CODE REVIEW

**Comment by MilosKozak** [comment]
make the toast message translatable pls. or pickup some already existing

**Comment by AdrianLxM** [comment]
Thanks for the catch. Updated it.

**Comment by MilosKozak** [comment]
i'd carefull with `this`. the fragment may not exist all the time. i hit this issue many times so i better use `MainApp.sResources.getString(....)` which always works

**Comment by MilosKozak** [comment]
the same with getString() .... i better use `MainApp.sResources.getString(...)`

**Comment by AdrianLxM** [comment]
Even if the fragment does not exist (or the GUI at all): `this` is an instance of a subclass of `Service` which is a context(Wrapper) by itself.

**Pull request merged**
