### PR TITLE
Remove sync to pump pref, always sync

### PR DESCRIPTION
**Pull request by jotomo**

### CODE REVIEW

**Comment by jotomo** [comment]
Tested with and works with the Combo.

**Comment by MilosKozak** [comment]
👍

**Comment by jotomo** [comment]
Added another commit - missed a spot in `NSProfilePlugin`.

**Comment by MilosKozak** [comment]
what with pumps not supporting profile update?

**Comment by jotomo** [comment]
That would only concern pumps that are added later on, since all currently supported pumps support profile update, right? They'd have to show a request to the user to manually update the profile, like you suggested.

**Comment by AdrianLxM** [comment]
@MilosKozak  with the Combo v2 driver, all real pumps do support setting profiles (with the Combo at least if the change is not too huge and it doesn't need too much time).

The two "virtual" pumps (virtual and MDI) have a method like this:
```
    @Override
    public int setNewBasalProfile(Profile profile) {
        // Do nothing here. we are using MainApp.getConfigBuilder().getActiveProfile().getProfile();
        return SUCCESS;
}
```

**Pull request merged**
