### PR TITLE
(WIP) First Implementation of a profile copying (from NS to Local)

### PR DESCRIPTION
**Pull request by triplem**
This implements copying a profile from NS to the local profile. Right now, it just copies the active profile.

### CODE REVIEW

**Comment by MilosKozak** [comment]
currently selected profile is hard to change. would be possible to select from list of available NS profiles?

**Comment by triplem** [comment]
Currently, i am trying to fix a couple of bugs on this one, but the button moved to the NS Profile, where it is shown next to the "Activate Profile" Button. The curently selected Profile is then copied. Guess that this will solve the above mentioned issue, no?

**Comment by MilosKozak** [comment]
ok. yes. it should be enough. 
i'm only not sure if getCurrentProfile() returns the one selected

**Comment by PoweRGbg** [comment]
@triplem  I just moved my code to the maintenance plugin and you moved it :) I will create a PR with the uploading LocalProfile to NS and you decide where to put it or comment here

**Comment by PoweRGbg** [comment]
I'm creating a new profile named "LocalProfile".

**Comment by triplem** [comment]
The logic is now fully integrated in the NSProfile Plugin. There is a button on the NS profile fragment now, which copies the currently selected profile to local.

**Comment by triplem** [comment]
@MilosKozak Me is using getSelectedItem() now, instead of the currentProfile. This makes it possible to select one profile and copy it to local, even if it is not active currently.

**Comment by triplem** [comment]
@PoweRGbg What happens, if the profile is existing already. Do you overwrite it?

**Comment by PoweRGbg** [comment]
@triplem It overwrites it, but still there is a "validFrom" field and it's appearing as a dropdown menu in NS Profile editor

**Comment by triplem** [comment]
I try to add the NS Upload as well. Thanks to @PoweRGbg, but help is really appreciated. I try to implement this without all the hassle of the additional DST Plugin, which is another PR then.

**Comment by MilosKozak** [comment]
copy from profile switches is now in dev

**Pull request closed without merging**
