### PR TITLE
Watch updater service worker thread

### LINKED ISSUE #679: Android killing AAPS due to misbehaving WatchUpdaterService
`WatchUpdaterService` is killed by Android after timing out. This kills AAPS entirely. From a quick look, it seems Android dislikes the service (`android.app.Service`, not an `IntentService`) running on the main thread and kills it after ~60s. xDrip+ has an interesting looking `startSelf` method in the same class we can probably learn from).
I saw these crashes roughly 4-6h apart, not sure how to trigger them (but enabling the _Log AndroidAPS start to NS_ helped in showing restarts in the graph).

[logcat-watchupdater-service-killed.txt](https://github.com/MilosKozak/AndroidAPS/files/1713483/logcat-watchupdater-service-killed.txt)

### PR DESCRIPTION
**Pull request by jotomo**
Fixes #679.

No crashes for the last 10h, usually they occur every 4-6h.
@gregorybel Could you test this as well, you experienced those crashes too.

### CODE REVIEW

**Comment by gregorybel** [comment]
yes will do, thanks a lot. can I simply cherrypick it into combo branch?

**Comment by jotomo** [comment]
@gregorybel Yes, just cherry-pick.

**Comment by jotomo** [comment]
No crashes during the night either. Seems like the NSClient crash is just a side effect, haven't seen any crashes there either.

**Comment by gregorybel** [comment]
1,5 days with only one restart, looks good!

**Comment by AdrianLxM** [comment]
The changes/commits are now included in https://github.com/MilosKozak/AndroidAPS/pull/734
It would be great if you could test it!

**Comment by gregorybel** [comment]
don't know what cause restart, was not fast enough to look at logcat. 
but I was too fast happy, since this morning 6 aaps start ☹️. strange... will feedback if I find something.

**Comment by AdrianLxM** [comment]
I like that this PR is tagged "merged" when https://github.com/MilosKozak/AndroidAPS/pull/734 was merged that included all commits :)
Thanks @jotomo

**Pull request merged**
