### PR TITLE
Add "status lights" and unify ribbon colors

### PR DESCRIPTION
**Pull request by schmitzn**
As discussed in #1097. The idea is to have reservoir, battery, insulin and catridge status on the homescreen. It works like a fire light: Dark grey (nothing to do), yellow (pay attention/warning), red (critical/empty ...). You can define your individual thresholds in nightscout and in the app preferences.

In my opinion this is very useful, because you see it all at a glance on your homescreen. So this is intended to prevent you from leaving the house without having enough insulin, or missing the battery alarm which came up at night when you were asleep.

Also, I've changed the colors of the top ribbon bar, inspired by @jotomo. So grey is the color for the default value and yellow/red are used to indicate a noteworthy state.

screenshot_20180616-141528

Thanks to @swissalpine as this is based on his sourcecode (and as he gave a lot of good suggestions).

### CODE REVIEW

**Comment by swissalpine** [comment]
:+1:
Thanks a lot for many source corrections!

**Comment by gregorybel** [comment]
looks really good!

Any chance to add an option so that we can Display as well the exact amount of X (days for battery, U for reservoir, etc....)

**Comment by swissalpine** [comment]
It's possible but why?
In my opinion there's no need for these informations on overview tab. We must pay attention to not overload this tab. A look at Careportal tab or Pump tab for this additional informations is not that problem. An alarm here should be enough.

**Comment by gregorybel** [comment]
yes in your opinion 😁
actually I need only battery and reservoir, not the rest. I run a low battery 6 days, number of days is more important than color. reservoir is the same, i need the number of U not a color.

**Comment by swissalpine** [comment]
Hm. I run a low battery in 36 days (energizer lithium) ... After a alarm I have two days rest ... And you can configure the reservoir level in two steps (yellow, red). Give it a try.

**Comment by AdrianLxM** [comment]
Shouldn't we have it in all layouts?

**Comment by schmitzn** [comment]
@AdrianLxM I think we don't need it in the NSClient layouts. But you're right, the smallheight layout was missing.

**Comment by triplem** [comment]
This one would pretty much close #1057. very nice one ;-)

**Comment by triplem** [comment]
On my screen there is a blank line between the "status light" line and the IOB-line. Furthermore the numbers on the left are incorrect for the senstitivity and the COB and IOB graphs. I have merged the latest "dev" beforehand.

**Comment by swissalpine** [comment]
Hallo Namensvetter, ;-)
the empty line was introduced by Milos, this should fix it:
https://github.com/MilosKozak/AndroidAPS/pull/1152
The other behaviour is related to the updates in the last two days and I couldn't imagine that this is "our" problem.

**Comment by wootmasterslick** [comment]
Very nice idea. I understand the mixup possibility with the RES/SEN mentioned above. Can I suggest to add an yellow icon of reservoir/ battery instead. Added benefit is that this is universally understandable throughout all languages.

**Comment by swissalpine** [comment]
Thank your for your feedback and the suggestion.
I - personally - didn't like a text line mixed with symbols. For me it's also a question of design, I wouldn't destroy the uniform appearance. If you find three letters which are less missleading, ok.
But I must confess that I couldn't understand the problem: This row displays only the status of consumables, I couldn't imagine that someone don't understand the logic and thinks that this also reflects sensitivity or resistance.

**Comment by wootmasterslick** [comment]
Insee you mention above that you think an alarm should be anough. I get your point, altough an alarm will be something that requires immediate action and might be annoying if it is also possible to view a warning text (like this example) or icon so that you have some more time to plan the action. E.g replace the insulin doent have to be at minmum level, you can do earlier and it would be unpleasant to have a repace insulin alarm i  the middle of the night.

Regarding your comment that it might be misleading I usually go by the practice that if only 1 person suggests that it might be misleading it probably is for some poeple. As we are developping for the whole community with also novice users it is best to mitigate any risk of confusion. Example is my girlfriend is using AAPS she is not experienced with computers so she benefits a lot from simple messages and icons.

**Comment by gregorybel** [comment]
can we merge this PR or is there any issues?

**Comment by swissalpine** [comment]
I'm running it for months now: Now issues!

Am Mo., 17. Sep. 2018 um 08:36 Uhr schrieb Grégory Beloncle <
notifications@github.com>:

**Comment by MilosKozak** [comment]
no new features to 2.0
i'd make this part of new AAPS design

**Comment by gregorybel** [comment]
would have been a good addition but I can understand your point.

**Comment by gregorybel** [comment]
@swissalpine  do you get it easily merged with dev or do you need to change a lot?

**Comment by schmitzn** [comment]
@gregorybel I'm running this with dev. Should be easy to merge.

**Comment by gregorybel** [comment]
ok, thank you!

**Comment by gregorybel** [comment]
@MilosKozak can we merge it now?

**Comment by gregorybel** [comment]
@schmitzn I tried yesterday to merge this branch with current dev but there are some conflicts. Could you please maybe rebase and fix the merge conflict?

**Comment by schmitzn** [comment]
@gregorybel sure, fixed now

**Comment by gregorybel** [comment]
thanks!

**Comment by gregorybel** [comment]
@schmitzn I saw in OverviewFragment.java there are new places where COLOR.X is used. Should this not be changed with new color scheme?

**Comment by CaroGo** [comment]
love it!

**Comment by savek-cc** [comment]
Please, please merge :)

**Comment by gregorybel** [comment]
screenshot_20190115-181202

Pimp it a bit, could PR this bid needed. But I had the feeling Milo wants to change completely UI?

**Comment by MasterPlexus** [comment]
> Pimp it a bit, could PR this bid needed. But I had the feeling Milo wants to change completely UI?

interesting, did it more or less in the same way, with additive color ;) But I think you are right due to the remark of futur UI... we will see...

image

**Comment by wootmasterslick** [comment]
Can you elaborate a bit more? What are the values next to it? Looks like you moved reservoir level also into the list, is this correct?
What are the things you changed?

Op 15 jan. 2019 om 18:14 heeft Grégory Beloncle <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


[screenshot_20190115-181202]<https://user-images.githubusercontent.com/24234385/51197230-3365b800-18f1-11e9-9920-45ea24699af0.jpg>

Pimp it a bit, could PR this bid needed. But I had the feeling Milo wants to change completely UI?

**Comment by MasterPlexus** [comment]
> Can you elaborate a bit more? What are the values next to it? Looks like you moved reservoir level also into the list, is this correct? What are the things you changed? 

I personally add in brackets the Days since the last change for CAN (cannula set), INS (insulin cartridge change), SEN (Sensor set) and BAT (battery change). RES is the rest of usable Insuline in the cartridge. As far as I can see, Gregorybel has used directly the hours in his mod, and not the Days.

**Comment by wootmasterslick** [comment]
> 
> 
> > Can you elaborate a bit more? What are the values next to it? Looks like you moved reservoir level also into the list, is this correct? What are the things you changed?
> 
> I personally add in brackets the Days since the last change for CAN (cannula set), INS (insulin cartridge change), SEN (Sensor set) and BAT (battery change). RES is the rest of usable Insuline in the cartridge. As far as I can see, Gregorybel has used directly the hours in his mod, and not the Days.

Perhaps a stupid question but I'd rather check.
Can I safely merge your code with the DEV branch and use it?

**Comment by MasterPlexus** [comment]
Did you ask for the pull here where we discussing, or did you mean my personal code? Anyway the branch of schmitzn or.my.personal ist valid against current dev-branch.

**Comment by wootmasterslick** [comment]
> 
> 
> Did you ask for the pull here where we discussing, or did you mean my personal code? Anyway the branch of schmitzn or.my.personal ist valid against current dev-branch.

I was referring to your personal code. Still new to the coding here and trying to figure out how I can best merge your implementation of the statuslights with latest dev. Perhaps you have tips ;-)  ?

**Comment by MasterPlexus** [comment]
For sure, contact me directly, and I can give you some hints. (Nospamming@web.de)

**Pull request merged**
