### PR TITLE
Fix for mixed up bage_warn, bage_urgent for Combo in Statuslights

### PR DESCRIPTION
**Pull request by swissalpine**
Fixes the small bug mentioned in https://github.com/MilosKozak/AndroidAPS/issues/2320

### CODE REVIEW

**Comment by gregorybel** [comment]
What are you fixing here?
Should not a warning value be smaller than an urgent value?
Why do you not simply change value in nightscout?

**Comment by swissalpine** [comment]
The first value is warn, the second urgent warn  and it is mixed up.

**Comment by swissalpine** [comment]
With this fix the warning value is smaller than the urgent warning value:
image

**Comment by gregorybel** [comment]
On my side nightscout values work.
Ok now got it, in handleAge, warn and urgent are inverted:


    void handleAge(String nsSettingPlugin, String eventName, TextView view, String text, int defaultUrgentThreshold, int defaultWarnThreshold)

**Comment by swissalpine** [comment]
Thanks for the hint, @gregorybel, so I changed handleAge() too and I adjusted the values to 244/336 as found in adjustAge().

**Comment by gregorybel** [comment]
you are welcomed.
But should we not invert at all place using method handleAge?

**Comment by swissalpine** [comment]
I'm not sure I understand your question correctly. In the Careportal the order is also warn - urgent. So now they are all in the same order, at least I think so ...

**Comment by gregorybel** [comment]
I mean, the method is called several times and I wonder if we should not Swap the values at each call

**Comment by swissalpine** [comment]
Many thanks for the explanation. This weekend I'm going to search if there are still functions with swapped values. At first sight I don't see any more.

**Comment by MilosKozak** [comment]
is this finished?

**Comment by swissalpine** [comment]
Yes, I think so. I haven't found any more.

**Pull request merged**
